networks:
  app_network:
    driver: bridge
  db_network:
    driver: bridge

services:

  postgres:
    image: postgres:16.1
    container_name: data_base
    volumes:
      - ./data_base:/var/lib/postgresql/data/
    expose:
      - POSTGRES_PORT
    env_file:
      - .env
    networks:
      - db_network
  

  pgadmin:
    image: dpage/pgadmin4
    container_name: pg_admin
    ports:
      - 5050:60
    volumes:
      - ./pg_admin:/var/lib/pgadmin
    env_file:
      - .env
    networks:
      - db_network
    depends_on:
      - postgres

  api:
    container_name: api
    build:
      context: ./services/api
      dockerfile: Dockerfile
    volumes:
      - ./services/api/:/api/
    ports:
      - 5010:5010
    env_file:
      - .env
    networks:
      - app_network

  cipher_service:
    container_name: cipher_service
    build:
      context: ./services/cipher_service
      dockerfile: Dockerfile
    volumes:
      - ./services/cipher_service/:/cipher_service/
    ports:
      - 5002:5002
    env_file:
      - .env
    networks:
      - app_network
  
  user_service:
    container_name: user_service
    build:
      context: ./services/user_service
      dockerfile: Dockerfile
    volumes:
      - ./services/user_service/:/user_service/
    ports:
      - 5001:5001
    env_file:
      - .env
    networks:
      - app_network
      - db_network
    depends_on:
      - postgres