networks:
  my_network:

services:

  develop: 
    build: 
      context: .
      dockerfile: .devcontainer/Dockerfile
    networks:
      - my_network
    volumes:
      - .:/workspace
    ports:
      - "8000:8000"
      - "8080:8080"
    